# Generated by Django 3.1.7 on 2021-03-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfiles',
            name='user_id',
            field=models.IntegerField(default='0'),
        ),
    ]
