# Generated by Django 3.1.7 on 2021-03-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210331_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfiles',
            name='user_id',
            field=models.IntegerField(default='1'),
        ),
    ]
